### ISSUE TITLE
Figure out how to shim jQuery libraries bundled via Browserify to WordPress's jQuery

### ISSUE THREAD

**Issue by ethanclevenger91** [webspec-design/wordpress-elixir#1]
Right now, if you use npm to install a jQuery plugin/extension and bundle it up with browserify, it doesn't know how to attach itself to the global jQuery the WordPress enqueues. Should be a way to shim this.

**Comment by webspecnick** [comment]
This may be fixed by updating to [Laravel Mix](https://github.com/JeffreyWay/laravel-mix) which uses Webpack instead of browserify. See [this issue about updating](https://github.com/webspec-design/wordpress-elixir/issues/3)

**Comment by webspecnick** [comment]
Closed due to webpack fixing this problem.
